
services:
  db:
    image: mysql:8.0
    container_name: springcrud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: springdb
      MYSQL_PASSWORD: ""

    ports:
      - "3306:3306"
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  app:
    image: spring-crud
    container_name: spring-crud
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/  springdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


    networks:
      - app-network

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge


